INSERT INTO PATIENT (PATIENT_NO, EMAIL, ENTRY_DATE, ENTRY_USER, FIRST_NAME, LAST_NAME, PHONE, UPDATE_DATE, UPDATE_USER) VALUES ('1', 'emranhos1@gmail.com', NOW(), '0001', 'Md. Emran', 'Hossain', '01670932273', NULL, NULL);
INSERT INTO PATIENT (PATIENT_NO, EMAIL, ENTRY_DATE, ENTRY_USER, FIRST_NAME, LAST_NAME, PHONE, UPDATE_DATE, UPDATE_USER) VALUES ('2', 'emranhos1@gmail.com', NOW(), '0001', 'AAA', 'AAA', '0167XXXXXXX', NULL, NULL);
INSERT INTO PATIENT (PATIENT_NO, EMAIL, ENTRY_DATE, ENTRY_USER, FIRST_NAME, LAST_NAME, PHONE, UPDATE_DATE, UPDATE_USER) VALUES ('3', 'emranhos1@gmail.com', NOW(), '0001', 'BBB', 'BBB', '0167XXXXXXX', NULL, NULL);
INSERT INTO PATIENT (PATIENT_NO, EMAIL, ENTRY_DATE, ENTRY_USER, FIRST_NAME, LAST_NAME, PHONE, UPDATE_DATE, UPDATE_USER) VALUES ('4', 'emranhos1@gmail.com', NOW(), '0001', 'CCC', 'CCC', '0167XXXXXXX', NULL, NULL);

-- UPDATE PATIENT SET GENDER_CODE = '1', NATIONALITY_CODE = '2' WHERE PATIENT_NO = '1';
-- UPDATE PATIENT SET GENDER_CODE = '2', NATIONALITY_CODE = '1' WHERE PATIENT_NO = '2';
-- UPDATE PATIENT SET GENDER_CODE = '3', NATIONALITY_CODE = '3' WHERE PATIENT_NO = '3';
-- UPDATE PATIENT SET GENDER_CODE = '4', NATIONALITY_CODE = '4' WHERE PATIENT_NO = '4';

INSERT INTO GENDER (SEX_CODE, ENTRY_DATE, ENTRY_USER, GENDER_NAME, SHORT_GENDER_NAME, UPDATE_DATE, UPDATE_USER) VALUES ('1', NOW(), '0001', 'MALE', 'M', NULL, NULL);
INSERT INTO GENDER (SEX_CODE, ENTRY_DATE, ENTRY_USER, GENDER_NAME, SHORT_GENDER_NAME, UPDATE_DATE, UPDATE_USER) VALUES ('2', NOW(), '0001', 'FEMALE', 'F', NULL, NULL);
INSERT INTO GENDER (SEX_CODE, ENTRY_DATE, ENTRY_USER, GENDER_NAME, SHORT_GENDER_NAME, UPDATE_DATE, UPDATE_USER) VALUES ('3', NOW(), '0001', 'UNKNOWN', 'U', NULL, NULL);
INSERT INTO GENDER (SEX_CODE, ENTRY_DATE, ENTRY_USER, GENDER_NAME, SHORT_GENDER_NAME, UPDATE_DATE, UPDATE_USER) VALUES ('4', NOW(), '0001', 'OTHER', 'O', NULL, NULL);

INSERT INTO NATIONALITY (NATIONALITY_CODE, ENTRY_DATE, ENTRY_USER, NATIONALITY_NAME, NATIONALITY_SHORT_NAME, UPDATE_DATE, UPDATE_USER) VALUES ('1', NOW(), '0001', 'AFGHANISTAN', 'AF', NULL, NULL);
INSERT INTO NATIONALITY (NATIONALITY_CODE, ENTRY_DATE, ENTRY_USER, NATIONALITY_NAME, NATIONALITY_SHORT_NAME, UPDATE_DATE, UPDATE_USER) VALUES ('2', NOW(), '0001', 'BANGLADESH', 'BD', NULL, NULL);
INSERT INTO NATIONALITY (NATIONALITY_CODE, ENTRY_DATE, ENTRY_USER, NATIONALITY_NAME, NATIONALITY_SHORT_NAME, UPDATE_DATE, UPDATE_USER) VALUES ('3', NOW(), '0001', 'CHINA', 'CI', NULL, NULL);
INSERT INTO NATIONALITY (NATIONALITY_CODE, ENTRY_DATE, ENTRY_USER, NATIONALITY_NAME, NATIONALITY_SHORT_NAME, UPDATE_DATE, UPDATE_USER) VALUES ('4', NOW(), '0001', 'DENMARK', 'DK', NULL, NULL);
INSERT INTO NATIONALITY (NATIONALITY_CODE, ENTRY_DATE, ENTRY_USER, NATIONALITY_NAME, NATIONALITY_SHORT_NAME, UPDATE_DATE, UPDATE_USER) VALUES ('5', NOW(), '0001', 'EGYPT', 'EG', NULL, NULL);
INSERT INTO NATIONALITY (NATIONALITY_CODE, ENTRY_DATE, ENTRY_USER, NATIONALITY_NAME, NATIONALITY_SHORT_NAME, UPDATE_DATE, UPDATE_USER) VALUES ('6', NOW(), '0001', 'FINLAND', 'FI', NULL, NULL);